-- Generated by Nexus UI from web/contract.ts. Do not edit: the next build overwrites it.

local type, pairs, getmetatable = type, pairs, getmetatable
local floor, huge, byte, utf8len = math.floor, math.huge, string.byte, utf8.len

-- A payload from the network is plain tables. Anything with a metatable is a wrapped value such
-- as a function reference and is refused, except what json.decode returns, which marks its
-- tables with __jsontype and is plain data that a handler may well pass on.
local function isTable(v)
    if type(v) ~= 'table' then return false end
    local meta = getmetatable(v)
    return meta == nil or (type(meta) == 'table' and meta.__jsontype ~= nil)
end

-- Integers are held to the range a JavaScript number can represent exactly, so a value means the
-- same thing on both sides of the bridge.
local function isInt(v)
    return type(v) == 'number' and v == floor(v) and v >= -9007199254740991 and v <= 9007199254740991
end

local function isNumber(v)
    return type(v) == 'number' and v == v and v ~= huge and v ~= -huge
end

local function unknownKey(path, key)
    local message = 'unknown key'
    if type(key) == 'string' and #key <= 40 then
        message = message .. ' "' .. key .. '"'
    end
    if path == '' then return message end
    return path .. ': ' .. message
end

local function charset(ranges)
    local set = {}
    for i = 1, #ranges, 2 do
        for code = byte(ranges, i), byte(ranges, i + 1) do set[code] = true end
    end
    return set
end

-- Matches text against a list of { set, min, max } steps. It walks the text once per step and
-- tracks every position the steps so far can end at, so the cost is steps * length whatever the
-- input: there is no backtracking for a crafted string to exploit.
local function matches(text, steps)
    local length = #text
    local reach = { [0] = true }
    for s = 1, #steps do
        local set, min, max = steps[s][1], steps[s][2], steps[s][3]
        local before = { 0 }
        for p = 0, length do
            before[p + 2] = before[p + 1] + (reach[p] and 1 or 0)
        end
        local nextReach, runStart, any = {}, 0, false
        for p = 0, length do
            if p > 0 and not set[byte(text, p)] then runStart = p end
            local from, to = p - max, p - min
            if from < runStart then from = runStart end
            if to >= from and before[to + 2] > before[from + 1] then
                nextReach[p] = true
                any = true
            end
        end
        if not any then return false end
        reach = nextReach
    end
    return reach[length] == true
end

local keys = {
    { shop = true },
    { label = true, balances = true, items = true },
    { cash = true, bank = true },
    { name = true, label = true, price = true },
    { missing = true },
    { shop = true, method = true, lines = true },
    { name = true, amount = true },
    { total = true, balances = true },
    { shop = true, images = true },
}

local enums = {
    { cash = true, bank = true },
}

local patterns = {
    { { charset('09__az'), 1, huge } },
    { { charset('09AZ__az'), 1, huge } },
}

NexusContract = {
    calls = {
        ['shop:catalogue'] = {
            limit = 6,
            per = 10,
            input = function(v)
                if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
                for k0 in pairs(v) do
                    if not keys[1][k0] then return false, unknownKey('', k0) end
                end
                do
                    local v1 = v.shop
                    if type(v1) ~= 'string' then return false, 'shop: expected a string' end
                    local n1 = utf8len(v1)
                    if not n1 then return false, 'shop: expected well-formed text' end
                    if n1 > 32 then return false, 'shop: expected at most 32 characters' end
                    if n1 < 1 then return false, 'shop: expected at least 1 character' end
                    if not matches(v1, patterns[1]) then return false, 'shop: expected text matching ^[a-z0-9_]+$' end
                end
                return true
            end,
            output = function(v)
                if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
                for k0 in pairs(v) do
                    if not keys[2][k0] then return false, unknownKey('', k0) end
                end
                do
                    local v1 = v.label
                    if type(v1) ~= 'string' then return false, 'label: expected a string' end
                    local n1 = utf8len(v1)
                    if not n1 then return false, 'label: expected well-formed text' end
                    if n1 > 48 then return false, 'label: expected at most 48 characters' end
                end
                do
                    local v1 = v.balances
                    if not isTable(v1) or v1[1] ~= nil then return false, 'balances: expected an object' end
                    for k1 in pairs(v1) do
                        if not keys[3][k1] then return false, unknownKey('balances', k1) end
                    end
                    do
                        local v2 = v1.cash
                        if not isInt(v2) then return false, 'balances.cash: expected an integer' end
                        if v2 < 0 then return false, 'balances.cash: expected at least 0' end
                    end
                    do
                        local v2 = v1.bank
                        if not isInt(v2) then return false, 'balances.bank: expected an integer' end
                        if v2 < 0 then return false, 'balances.bank: expected at least 0' end
                    end
                end
                do
                    local v1 = v.items
                    if not isTable(v1) then return false, 'items: expected an array' end
                    local n1 = 0
                    for _ in pairs(v1) do
                        n1 = n1 + 1
                        if n1 > 64 then return false, 'items: expected at most 64 items' end
                    end
                    for i1 = 1, n1 do
                        local v2 = v1[i1]
                        if not isTable(v2) or v2[1] ~= nil then return false, 'items[' .. i1 .. ']: expected an object' end
                        for k2 in pairs(v2) do
                            if not keys[4][k2] then return false, unknownKey('items[' .. i1 .. ']', k2) end
                        end
                        do
                            local v3 = v2.name
                            if type(v3) ~= 'string' then return false, 'items[' .. i1 .. '].name: expected a string' end
                            local n3 = utf8len(v3)
                            if not n3 then return false, 'items[' .. i1 .. '].name: expected well-formed text' end
                            if n3 > 48 then return false, 'items[' .. i1 .. '].name: expected at most 48 characters' end
                            if n3 < 1 then return false, 'items[' .. i1 .. '].name: expected at least 1 character' end
                            if not matches(v3, patterns[2]) then return false, 'items[' .. i1 .. '].name: expected text matching ^[A-Za-z0-9_]+$' end
                        end
                        do
                            local v3 = v2.label
                            if type(v3) ~= 'string' then return false, 'items[' .. i1 .. '].label: expected a string' end
                            local n3 = utf8len(v3)
                            if not n3 then return false, 'items[' .. i1 .. '].label: expected well-formed text' end
                            if n3 > 64 then return false, 'items[' .. i1 .. '].label: expected at most 64 characters' end
                        end
                        do
                            local v3 = v2.price
                            if not isInt(v3) then return false, 'items[' .. i1 .. '].price: expected an integer' end
                            if v3 < 1 then return false, 'items[' .. i1 .. '].price: expected at least 1' end
                        end
                    end
                end
                return true
            end,
            errors = {},
        },
        ['shop:checkout'] = {
            limit = 4,
            per = 10,
            input = function(v)
                if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
                for k0 in pairs(v) do
                    if not keys[6][k0] then return false, unknownKey('', k0) end
                end
                do
                    local v1 = v.shop
                    if type(v1) ~= 'string' then return false, 'shop: expected a string' end
                    local n1 = utf8len(v1)
                    if not n1 then return false, 'shop: expected well-formed text' end
                    if n1 > 32 then return false, 'shop: expected at most 32 characters' end
                    if n1 < 1 then return false, 'shop: expected at least 1 character' end
                    if not matches(v1, patterns[1]) then return false, 'shop: expected text matching ^[a-z0-9_]+$' end
                end
                do
                    local v1 = v.method
                    if type(v1) ~= 'string' or not enums[1][v1] then return false, 'method: expected one of "cash", "bank"' end
                end
                do
                    local v1 = v.lines
                    if not isTable(v1) then return false, 'lines: expected an array' end
                    local n1 = 0
                    for _ in pairs(v1) do
                        n1 = n1 + 1
                        if n1 > 24 then return false, 'lines: expected at most 24 items' end
                    end
                    if n1 < 1 then return false, 'lines: expected at least 1 item' end
                    for i1 = 1, n1 do
                        local v2 = v1[i1]
                        if not isTable(v2) or v2[1] ~= nil then return false, 'lines[' .. i1 .. ']: expected an object' end
                        for k2 in pairs(v2) do
                            if not keys[7][k2] then return false, unknownKey('lines[' .. i1 .. ']', k2) end
                        end
                        do
                            local v3 = v2.name
                            if type(v3) ~= 'string' then return false, 'lines[' .. i1 .. '].name: expected a string' end
                            local n3 = utf8len(v3)
                            if not n3 then return false, 'lines[' .. i1 .. '].name: expected well-formed text' end
                            if n3 > 48 then return false, 'lines[' .. i1 .. '].name: expected at most 48 characters' end
                            if n3 < 1 then return false, 'lines[' .. i1 .. '].name: expected at least 1 character' end
                            if not matches(v3, patterns[2]) then return false, 'lines[' .. i1 .. '].name: expected text matching ^[A-Za-z0-9_]+$' end
                        end
                        do
                            local v3 = v2.amount
                            if not isInt(v3) then return false, 'lines[' .. i1 .. '].amount: expected an integer' end
                            if v3 < 1 then return false, 'lines[' .. i1 .. '].amount: expected at least 1' end
                            if v3 > 50 then return false, 'lines[' .. i1 .. '].amount: expected at most 50' end
                        end
                    end
                end
                return true
            end,
            output = function(v)
                if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
                for k0 in pairs(v) do
                    if not keys[8][k0] then return false, unknownKey('', k0) end
                end
                do
                    local v1 = v.total
                    if not isInt(v1) then return false, 'total: expected an integer' end
                    if v1 < 1 then return false, 'total: expected at least 1' end
                end
                do
                    local v1 = v.balances
                    if not isTable(v1) or v1[1] ~= nil then return false, 'balances: expected an object' end
                    for k1 in pairs(v1) do
                        if not keys[3][k1] then return false, unknownKey('balances', k1) end
                    end
                    do
                        local v2 = v1.cash
                        if not isInt(v2) then return false, 'balances.cash: expected an integer' end
                        if v2 < 0 then return false, 'balances.cash: expected at least 0' end
                    end
                    do
                        local v2 = v1.bank
                        if not isInt(v2) then return false, 'balances.bank: expected an integer' end
                        if v2 < 0 then return false, 'balances.bank: expected at least 0' end
                    end
                end
                return true
            end,
            errors = {
                not_enough_money = function(v)
                    if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
                    for k0 in pairs(v) do
                        if not keys[5][k0] then return false, unknownKey('', k0) end
                    end
                    do
                        local v1 = v.missing
                        if not isInt(v1) then return false, 'missing: expected an integer' end
                        if v1 < 1 then return false, 'missing: expected at least 1' end
                    end
                    return true
                end,
            },
        },
    },
    pushes = {},
    client = {},
    state = {},
    screens = {
        shop = function(v)
            if not isTable(v) or v[1] ~= nil then return false, 'expected an object' end
            for k0 in pairs(v) do
                if not keys[9][k0] then return false, unknownKey('', k0) end
            end
            do
                local v1 = v.shop
                if type(v1) ~= 'string' then return false, 'shop: expected a string' end
                local n1 = utf8len(v1)
                if not n1 then return false, 'shop: expected well-formed text' end
                if n1 > 32 then return false, 'shop: expected at most 32 characters' end
                if n1 < 1 then return false, 'shop: expected at least 1 character' end
                if not matches(v1, patterns[1]) then return false, 'shop: expected text matching ^[a-z0-9_]+$' end
            end
            do
                local v1 = v.images
                if not isTable(v1) then return false, 'images: expected an object' end
                local n1 = 0
                for _ in pairs(v1) do
                    n1 = n1 + 1
                    if n1 > 64 then return false, 'images: expected at most 64 entries' end
                end
                for k1, v2 in pairs(v1) do
                    local c1 = type(k1) == 'string' and utf8len(k1)
                    if not c1 or c1 > 64 then return false, 'images: expected text keys of at most 64 characters' end
                    if type(v2) ~= 'string' then return false, 'images.' .. k1 .. ': expected a string' end
                    local n2 = utf8len(v2)
                    if not n2 then return false, 'images.' .. k1 .. ': expected well-formed text' end
                    if n2 > 300 then return false, 'images.' .. k1 .. ': expected at most 300 characters' end
                end
            end
            return true
        end,
    },
}
