-- Generated by Nexus UI from the <screen> tags in web/screens. Do not edit: the next build overwrites it.

NexusScreens = {
    shop = { layer = 'screen', mouse = true, keyboard = true, keepInput = false, escape = true },
}
